### ISSUE TITLE
Too many surfaces error (texinfo maximum)

### ISSUE THREAD

**Issue by Ypsckud** [yquake2/yquake2remaster#1]
There seems to be a 8192 texinfo maximum in the engine. Can it be increased?

**Comment by 0lvin** [comment]
@Ypsckud Could you please check with https://github.com/yquake2/yquake2remaster/commit/bd19960ddfcf84cc59077aee9339a99383d7c01b ? 

Code has allocated memory for map dynamically, (except count of submodels and one place for Leafs), it should be enough to load any maps.

Only GL1 and VK are checked with some random maps from ReRelease. Other renders has issues with wall lights. GL1 sometime has broken images after load maps, so it's known bug. I am checking what is wrong image allocation, maybe some limit or hard-coded value.

**Comment by 0lvin** [comment]
@Ypsckud do you need windows binaries for test?

Could you please reopen issue if it is still reproduced?
