### ISSUE TITLE
other problem

### ISSUE THREAD

**Issue by acyc070** [yquake2/yquake2remaster#10]
z@z-\M-O\M-J:pty0 + /dfg: make                                                           [14:28:48]
Build configuration
============================
YQ2_ARCH = x86_64 COMPILER = gcc
WITH_CURL = yes
WITH_OPENAL = yes
WITH_RPATH = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR =
============================

===> Building yquake2.exe
make release/yquake2.exe
make[1]: Verzeichnis „/dfg“ wird betreten
===> CC src/backends/generic/misc.c
/bin/sh: -c: Zeile 1: Syntaxfehler beim unerwarteten Symbol »(«
/bin/sh: -c: Zeile 1: `cc -c -O2 -Wall -pipe -fomit-frame-pointer -fno-strict-aliasing -fwrapv -fvisibility=hidden -MMD -Wno-format-truncation -Wno-format-overflow -DYQ2OSTYPE=\"Windows\" -DYQ2ARCH=\"x86_64\" -mfpmath=sse -ffp-contract=off -DUSE_CURL -DAVMEDIADECODE -DUSE_OPENAL -DDEFAULT_OPENAL_DRIVER='"openal32.dll"' -IC:/Users/z/Downloads/quake2-buildenv-20230701 (1)/buildenv/mingw64/include/SDL2 -Dmain=SDL_main -DNOUNCRYPT -I/usr/include -o build/client/src/backends/generic/misc.o src/backends/generic/misc.c'
make[1]: *** [Makefile:440: build/client/src/backends/generic/misc.o] Fehler 2
make[1]: Verzeichnis „/dfg“ wird verlassen
make: *** [Makefile:433: client] Fehler 2
zsh: exit 2     make
make  1,29s user 5,92s system 70% cpu 10,252 total

**Comment by acyc070** [comment]
PLEASE ANSWER!

**Comment by acyc070** [comment]
tried clean msys2
In file included from C:/msys64/mingw64/include/winsock.h:36,
                 from C:/msys64/mingw64/include/windows.h:92,
                 from src/backends/generic/misc.c:42:
C:/msys64/mingw64/include/psdk_inc/_fd_types.h:100:2: warning: #warning "fd_set and associated macro
s have been defined in sys/types.      This can cause runtime problems with W32 sockets" [-Wcpp]
  100 | #warning "fd_set and associated macros have been defined in sys/types.  \
      |  ^~~~~~~
C:/msys64/mingw64/include/winsock.h:299:34: error: conflicting types for 'select'; have 'int(int,  f
d_set *, fd_set *, fd_set *, const TIMEVAL *)' {aka 'int(int,  fd_set *, fd_set *, fd_set *, const s
truct timeval *)'}
  299 |   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set *writefds,fd_set *ex
ceptfds,const TIMEVAL *timeout);
      |                                  ^~~~~~
In file included from C:/msys64/usr/include/sys/types.h:50,
                 from C:/msys64/usr/include/time.h:28,
                 from src/backends/generic/../../common/header/shared.h:39,
                 from src/backends/generic/misc.c:30:
C:/msys64/usr/include/sys/select.h:80:5: note: previous declaration of 'select' with type 'int(int,
 fd_set *, fd_set *, fd_set *, struct timeval *)'
   80 | int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,
      |     ^~~~~~
make[1]: *** [Makefile:440: build/client/src/backends/generic/misc.o] Error 1
make[1]: Leaving directory '/c/Users/z/Downloads/yquake2remaster-master (10)/yquake2remaster-master'
make: *** [Makefile:433: client] Error 2

**Comment by 0lvin** [comment]
It looks like incorrect version of gcc, could you please check that you have 64bit version of packages and have used 64 bit msysshell? Required packages is listed [here](https://github.com/yquake2/yquake2remaster/blob/079267996dbb42f1876d003dfdc1d8811ce93845/.github/workflows/windows.yml#L27). It must be exactly mingw-w64-x86_64-gcc version of gcc.

**Comment by acyc070** [comment]
![Screenshot (119)](https://github.com/yquake2/yquake2remaster/assets/112773735/a1b799c2-8827-41ed-865b-f6bf212bbcb8)

**Comment by 0lvin** [comment]
MSBuild/MS Visual Studio are [unsupported](https://github.com/yquake2/yquake2/issues/984).

**Comment by acyc070** [comment]
can you explain what the “unexpected symbol »(«” is?

**Comment by acyc070** [comment]
I'm still can't build on Windows because "unexpected symbol »(«"

**Comment by Yamagi** [comment]
> `-IC:/Users/z/Downloads/quake2-buildenv-20230701 (1)/buildenv/mingw64/include/SDL2`

The Makefiles are build with Unix in mind and don't support pathes which are too "windowsly". Is that even a word? ;) Remove the spaces and all non-ASCII characters from the path.

**Comment by 0lvin** [comment]
Could you please reopen issue if still have issues with code compilation?
