### ISSUE TITLE
[DOUBT] Renderers

### ISSUE THREAD

**Issue by SilentMRG** [yquake2/yquake2remaster#11]
Hello...

What renderers are supported by this port? I saw something about OpenGL 3.2, but, will this run in OpenGL 2.1 or in Software mode? Just giving an example. I ask this because the standard version of the source port runs perfectly on the 13 year old hardware I have here, hehe.

Thanks in advance!

**Comment by 0lvin** [comment]
Code contains OpenGL1, OpenGLES 3.2, OpenGL 3.2, OpenGL 4.6, Vulkan and Soft renders.

OpenGL 1 and Vulkan renders are recommended for now as have less possible glitches. Issues are mostly related to game logic itself than render logic, like some monsters have different behaviour or incorrect spawn player on level. 

Other renders has render issues, like gl3* renders could have light map issues on some levels, gl4 additionally could have issues with models renders, soft render does not support light maps and has artifacts.

Look to [video](https://youtu.be/Slf3iPLK-40) with latest state or such little bit [outdated video](https://youtu.be/1Lq2Q0M3pLU).

**Comment by 0lvin** [comment]
Code uses exactly same textures as defined in updated Rerelease map, models and light map formats. In same time code uses old effects and features as provided by original Quake 2 code and mods. As result it does not have updated effects and logic, e.g.: fire effects, texture materials, compass, fog, translate, path find logic, new lights and poi entities and so on. Some of it could  be implemented as we have open-source game logic code and described in documentation. And some of the features will be never implemented as not described anywhere or required full code rewrite, like replicate API/ABI of Rerelease libraries.
