### ISSUE TITLE
md3 not importing

### ISSUE THREAD

**Issue by acyc070** [yquake2/yquake2remaster#13]
non corrupted md3 imports with error "filesize(numbers) is smaller than(numbers)"

**Comment by acyc070** [comment]
i checked, file imports fully correctly with blender

**Comment by 0lvin** [comment]
Could you please share link to model or attach example?

**Comment by acyc070** [comment]
[ssmnsjis.zip](https://github.com/yquake2/yquake2remaster/files/14620587/ssmnsjis.zip)

**Comment by acyc070** [comment]
I checked this model with ioquake3 it's working successfully. Something wrong with yquake2remaster

**Comment by acyc070** [comment]
is anyone here?

**Comment by 0lvin** [comment]
Have you used code from master branch? what commit have used if you have built from source? 

What version of operation system have used? 

> non corrupted md3 imports with error "filesize(numbers) is smaller than(numbers)"

Latest code in master does not have such message, maybe 'filesize to small,should be'. Could you please share whole log with cvar `developer` set one.

I have tried you model and model is loaded and have 58 frames and have internal end_ofs as 1801924, that is fully same as correct file size.

**Comment by DanielGibson** [comment]
> is anyone here?

dude, this is not some kind of live chat.
you can't expect developers to reply within hours, this is just a hobby project
