### ISSUE TITLE
MD3 Fix

### ISSUE THREAD

**Issue by acyc070** [yquake2/yquake2remaster#15]
I checked the functionality of the md3 loader on a random model from quake 3 and an error occurred. *.md3 file has incorrect frames count -(numbers)(asterisks)

**Comment by 0lvin** [comment]
Could please share such information?
* Operation system version,
* code version,
* full log with cvar developer flag set to one,
* model file that produce error,
* expected count frames/vert/triangles in file,
* have compiled code by yourself or have used files from release page?

**Comment by acyc070** [comment]
windows 11,
code version latest,
[log.zip](https://github.com/yquake2/yquake2remaster/files/14652328/log.zip)
i expected model will just load,
i compiled code by myself

**Comment by acyc070** [comment]
I'll wait till it'll be fixed

**Comment by 0lvin** [comment]
I can't reproduce issues with win32 and win64 builds.

Have you tried with release [windows binaries](https://github.com/yquake2/yquake2remaster/releases/download/8.31RR5/yquake2remaster-x86_64-8.31RR5.zip)?

Have you used https://deponie.yamagi.org/quake2/windows/buildenv/ as build environment?

**Comment by acyc070** [comment]
i used build environment

**Comment by acyc070** [comment]
the bug fixed itself. magic? don't know
