### ISSUE TITLE
`R_RecursiveLightPoint` returning total black color when `DECOUPLED_LM` lump is present

### ISSUE THREAD

**Issue by BraXi** [yquake2/yquake2remaster#16]
Entities are completly black when `DECOUPLED_LM` lump is present but `LIGHTGRID_OCTREE` is not.

The dot products in `R_RecursiveLightPoint` are calculated wrong when `DECOUPLED_LM` is used thus the function returns with `-1` (never finds a lightmap pixel), which in turns makes `R_LightPoint` always return total black color. 

You're probably being saved by lightgrid lookup which makes `R_LightPoint` return early on maps compiled with it :)

Changing two lines seems to solve the issue.

This line:
https://github.com/yquake2/yquake2remaster/blob/51407d7139d6b7215a3eb6d44b88a0abffcd2ac8/src/client/refresh/files/light.c#L167
Should be:
```C
		s = DotProduct(mid, surf->lmvecs[0]) + surf->lmvecs[0][3];
```

And this one:
https://github.com/yquake2/yquake2remaster/blob/51407d7139d6b7215a3eb6d44b88a0abffcd2ac8/src/client/refresh/files/light.c#L168

should be:
```C
		t = DotProduct(mid, surf->lmvecs[1]) + surf->lmvecs[1][3];
```

**Comment by 0lvin** [comment]
Could you please map example for test?

**Comment by BraXi** [comment]
Okay, I've relit `hangarold` to demonstrate bug using latest ericw-tools alpha

This is original `old/hangarold.bsp` as is in q2 remaster:
![hangarold-orig](https://github.com/yquake2/yquake2remaster/assets/6434152/a8872939-79d8-4fc8-adb7-414bc8cb1231)

This is relit version with decoupledlm with twice the lightmap resolution `light -threads 8 -extra -bounce -dirt -world_units_per_luxel 8`
![hangarold-relit](https://github.com/yquake2/yquake2remaster/assets/6434152/ea574c57-d110-45b7-aeb7-f5c3250b9800)

And this version of `hangarold` is with lightgrid and decoupledlm:
`light -threads 8 -extra -bounce -dirt -lightgrid -lightgrid_dist 32 32 32 -world_units_per_luxel 8`
![hangarold-grid](https://github.com/yquake2/yquake2remaster/assets/6434152/016858f8-dfcc-4d2c-9837-505b9a40f6ad)


The two first screenshots show busted `R_RecursiveLightPoint`

**Comment by 0lvin** [comment]
Fix for gl/vk code has broke soft render light, I am looking to it. It looks like soft needs more unification with other renders.

**Comment by BraXi** [comment]
I am away from PC, but maybe lmvecs are not set by these renderers?

**Comment by 0lvin** [comment]
Should be fixed in https://github.com/yquake2/yquake2remaster/releases/tag/8.31RR6
