### ISSUE TITLE
`R_MarkSurfaceLights` hides global variable `r_dlightframecount`

### ISSUE THREAD

**Issue by BraXi** [yquake2/yquake2remaster#17]
https://github.com/yquake2/yquake2remaster/blob/84f5fd2c97d11238363ed527870943b57736ad40/src/client/refresh/files/light.c#L703

Idealy just rename arg `r_dlightframecount` to something else

https://github.com/yquake2/yquake2/issues/1093

**Comment by 0lvin** [comment]
Should be fixed in https://github.com/yquake2/yquake2remaster/commit/99f80e12cdd1210cba3a1a61c346088b144e13ac
