### ISSUE TITLE
[Sound] Arbitrary music track names

### ISSUE THREAD

**Issue by SirYodaJedi** [yquake2/yquake2remaster#18]
As if the Ogg loading code wasn't complicated enough, apparently the remaster supports arbitrary music track filenames, using it for `ndctf0`. Glancing at `ogg.c`, it appears YQ2R currently only supports `track%02i` or `Track%02i`.

Per @Paril on Discord:
![image](https://github.com/yquake2/yquake2remaster/assets/50331474/912751c1-c375-4953-887b-caa0fd24506a)
![image](https://github.com/yquake2/yquake2remaster/assets/50331474/489fe168-8a8f-4eee-a93c-f08c072adce2)

**Comment by 0lvin** [comment]
By quick look, it looks like it requires not only changes in ogg.c but also add support of sounds attribute to entity in game code itself. Look to usage of CD_TRACk in g_spawn in published ReRelease code and original code.

**Comment by 0lvin** [comment]
Could you please check with https://github.com/yquake2/yquake2remaster/releases/tag/8.31RR7 ? Code has additional workaround to play music file track by name instead number, it should play such custom track on load of `ndctf0` map.

**Comment by SirYodaJedi** [comment]
Works.
