### ISSUE TITLE
[Feature Request] Add Support for the Q2 Mission Pack "Call of the Machine" from Q2 Remastered

### ISSUE THREAD

**Issue by MasterO2** [yquake2/yquake2remaster#2]
@Yamagi 

https://en.wikipedia.org/wiki/Quake_II#Enhanced_version_and_Call_of_the_Machine

In the recent remaster of Quake 2, they added a new mission pack called `Call of the Machine`.  Since this is an official mission pack, it should be supported by Yamagi Quake.

(On a semi-related note, Quakespasm and other Quake 1 source ports support the mission pack `Dimension of the Machine` from `Quake Enhanced`, so there's precedent).

**Comment by MasterO2** [comment]
@Yamagi For what it's worth: https://github.com/id-Software/quake2-rerelease-dll

**Comment by 0lvin** [comment]
@MasterO2 Do you need windows binaries for alpha version with new asset support?

**Comment by 0lvin** [comment]
Alpha build is released https://github.com/yquake2/yquake2remaster/releases/tag/8.21RR1

Discussion could be continued in #3
