### ISSUE TITLE
fix it

### ISSUE THREAD

**Issue by acyc070** [yquake2/yquake2remaster#20]
shortly:weapon.md2 exist -> player model exist. weapon.md2 didn't exist -> player model didn't exist. *_i.pcx exist -> skin exist. *_i.pcx didn't exist -> skin didn't exist.

disable requirement for "weapon.md2" and "*_i.pcx" files in player folder. if "weapon.md2" is not in folder or corrupted, this game thinks that player model didn't even exist. even if tris.md2 there(i tried using "skin" command... didn't work). if "icon (_i) " for skin not there. this game thinks that skin didn't exist. even if "base" skin there

**Comment by 0lvin** [comment]
It's part of requirements for preview model, all three kind of files must be in directory to be correct player model to select. There could be files with different related formats in directory, skin and icon could be pcx, PNG and m8, weapon and player could be md5mesh, md3, FM, MDX, MDL and md2.
