### ISSUE TITLE
Lost Station exit problem.

### ISSUE THREAD

**Issue by Sind6ex** [yquake2/yquake2remaster#22]
HI! Got this message exiting Lost Station Quake2:
-===================================-

Lost Station
Downloading sound/misc/ddamage1.wav
Server does not have this file.
Downloading pics/w_grapple.pcx
Server does not have this file.
Map: train
Map maps/train.bsp IBSP with version 38 (Quake2 ReRelease)                   
------- server initialization ------                                         
Map maps/base3.bsp IBSP with version 38 (Quake2 ReRelease)
.ent file maps/base3@1597.ent loaded.
46 entities inhibited.
0 teams repaired
0 teams with 0 entities.
********************
ERROR: Game Error: ReadField: function _blocked not found in table, can't load game
********************
==== ShutdownGame ====

Have a nice day. Slava Ukraini!

**Comment by 0lvin** [comment]
Have you had `viewpos` near to 143, 1748, -833 and map equal to `base3` before error?

**Comment by Sind6ex** [comment]
Yes of course before I entered Lost Station. Are you serious?

**Comment by 0lvin** [comment]
I can't reproduce it with Linux build. 

Have you used binary windows build?

I assume that error could be related to saves. Could you please try without saves and additional mods or pak files?

**Comment by Sind6ex** [comment]
Hi Denis! Now I'm sure it had something to do with the saves and I didn't need to remove the addon. Another bug you may already know about is at the Lost Train position: -983 -935 -233 gondola behavior one is right the other weird.

**Comment by 0lvin** [comment]
Hi, thank you. I will look.

Code in last release should correctly work for platforms with original Quake 2 assets.

ReRelease assets have different flags for platforms as result all moving platforms appears in unexpected places, i have ported some of such flags and need to recheck that it fixes platform issues or just create some regression for old mods.

**Comment by 0lvin** [comment]
Could you please check with latest master, and reopen bug if its still valid?

**Comment by Sind6ex** [comment]
Hello and have a good Holiday!
Since you are asking if there is still a problem, as I previously stated, I have tested and the problem does not persist.
