### ISSUE TITLE
Error C2036 'void *': unknown size	yquake2	.\yquake2remaster\src\common\filesystem.c 658

### ISSUE THREAD

**Issue by HuubVanAmelsvoort** [yquake2/yquake2remaster#30]
When I build the environment and open it with VS2022, I get 11 errors example the following:
Severity Code Description Project File Line Suppression State Details
Error C2036 'void *': unknown size yquake2 D:\werkdirectory\VSProjecten\yquake2remaster\src\common\filesystem.c 658.
Did I do something wrong?

Windows10, the following output when building the sln etc.:

>cmake -G "Visual Studio 17 2022" -A x64 -DYQUAKE2LIBS=".\dhewm3-libs\x86_64-w64-mingw32" .\yquake2remaster

. = locations dir.

CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required): Compatibility with CMake < 3.5 will be removed from a future version of CMake.

Update the VERSION argument <min> value or use a ...<max> suffix to tell CMake that the project does not need compatibility with older versions.

NOTICE: The CMakeLists.txt is unmaintained. Use the Makefile if possible.
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.41.34120.0 
-- Detecting C compiler ABI info 
-- Detecting C compiler ABI info - done 
-- Check for working C compiler: d:/Programs/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped 
-- Detecting C compile features 
-- Detecting C compile features - done 
-- Setting YQ2OSTYPE to "Windows" - NOT setting YQ2ARCH, because we're targeting MSVC (VisualC++) 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed 
-- Looking for pthread_create in pthreads 
-- Looking for pthread_create in pthreads - not found 
-- Looking for pthread_create in pthread 
-- Looking for pthread_create in pthread - not found 
-- Found Threads: TRUE 
-- Found SDL2: ./dhewm3-libs/x86_64-w64-mingw32/lib/SDL2main.lib;./dhewm3-libs/x86_64-w 64-mingw32/lib/SDL2.lib 
-- Found OpenGL: opengl32 
-- Looking for backtrace 
-- Looking for backtrace - not found 
-- Looking for backtrace in execinfo 
-- Looking for backtrace in execinfo - not found 
-- Found CURL: ./dhewm3-libs/x86_64-w64-mingw32/lib/libcurl.lib (found version "8.0.1") 
-- Found OpenAL: ./dhewm3-libs/x86_64-w64-mingw32/lib/OpenAL32.lib 
-- Configuring done (12.1s) 
-- Generating donated (0. 2s) 
-- Build files have been written to: ./yquake2remaster

**Comment by 0lvin** [comment]
Build on windows has been tested with mingw64 + gcc only. 

Cmake and msvc are not supported.

**Comment by DanielGibson** [comment]
Doesn't change the fact that 
```c
void *buffer;
// ...
memmove(buffer + written, comressed_buffer + read, x + 1);
```
or specifically `buffer + written` is not portable C code (probably not even valid).
You should cast `buffer` to `byte*` for that operation.

**Comment by 0lvin** [comment]
oops, my fault, fixed. thank you
