### ISSUE TITLE
Make build not working

### ISSUE THREAD

**Issue by fighterguard** [yquake2/yquake2remaster#31]
Following the instructions in makefile (just type "make") I get the following error:

```
process_begin: CreateProcess(NULL, sdl2-config --cflags, ...) failed.
Makefile:289: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, sdl2-config --libs, ...) failed.
Makefile:382: pipe: Bad file descriptor
Build configuration
============================
YQ2_ARCH = x86_64 COMPILER = unknown
WITH_CURL = yes
WITH_OPENAL = yes
WITH_AVCODEC = yes
WITH_RPATH = yes
WITH_SDL3 = no
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR = 
============================

===> Building yquake2.exe
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe release/yquake2.exe
make[1]: Entering directory 'D:/Projects/Code/yquake2remaster'
process_begin: CreateProcess(NULL, sdl2-config --cflags, ...) failed.
Makefile:289: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, sdl2-config --libs, ...) failed.
Makefile:382: pipe: Bad file descriptor
===> CC src/backends/generic/misc.c
process_begin: CreateProcess(NULL, cc -c -O2 -Wall -pipe -fomit-frame-pointer -fno-strict-aliasing -fwrapv -fvisibility=hidden -MMD -DYQ2OSTYPE=\"Windows\" -DYQ2ARCH=\"x86_64\" -mfpmath=sse -DUSE_CURL -DAVMEDIADECODE -DUSE_OPENAL -DDEFAULT_OPENAL_DRIVER=\"openal32.dll\" -DNOUNCRYPT -I/usr/include -o build/client/src/backends/generic/misc.o src/backends/generic/misc.c, ...) failed. 
make (e=2): The system cannot find the file specified.
make[1]: *** [Makefile:468: build/client/src/backends/generic/misc.o] Error 2
make[1]: Leaving directory 'D:/Projects/Code/yquake2remaster'
make: *** [Makefile:461: client] Error 2
```
This is my version of make
```
GNU Make 4.4.1
Built for Windows32
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Please help.

Thank you.

**Comment by 0lvin** [comment]
It looks like you dont have correct compiler and build environment, could you please check that you have used mingw64 and installed all packages from https://github.com/yquake2/yquake2remaster/blob/master/.github/workflows/win64.yml. ?

Build on windows are only tested with mingw64 + gcc.

**Comment by HuubVanAmelsvoort** [comment]
After the solution from Olvin #30 its working also with vs2022 with:
cmake -G "Visual Studio 17 2022" -A x64 -DYQUAKE2LIBS=".\dhewm3-libs\x86_64-w64-mingw32" .\yquake2remaster

The . is where your source and library is.
So going from vs2022 to developer command prompt.

**Comment by fighterguard** [comment]
@0lvin Thank you very much!
As a suggestion in order to close this issue, it would be great if this, and other compilation related FAQs (like the fact that CmakeLists is not maintained anymore, and could break at any moment) to a dedicated .md file for easy future reference?

**Comment by fighterguard** [comment]
@HuubVanAmelsvoort It looks like mingw32 is still required besides VS2022. Also, I keep getting the `void * unknown size` error.
It seems that MSVC is not a viable environment for this project.

**Comment by fighterguard** [comment]
@HuubVanAmelsvoort BTW, I always get this error `CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)`
  I've never been able to figure out that one. Which files is it expecting? Where should I put those files? Where do I get those files from? I've tried so many things, and searched far and wide, and I've never found any sort of clear answer to this. And not just with this project. Every project that uses SDL has the same problem for me. I think it shouldn't be so difficult to figure out.

**Comment by fighterguard** [comment]
@0lvin Trying with mingw and msys, I keep getting this error:
´´´
===> Building yquake2.exe
make release/yquake2.exe
make[1]: Entering directory '/d/Projects/Code/yquake2remaster'
make[1]: sdl2-config: No such file or directory
make[1]: sdl2-config: No such file or directory
===> CC src/client/cl_cin.c
make[1]: cc: No such file or directory
make[1]: *** [Makefile:468: build/client/src/client/cl_cin.o] Error 127
make[1]: Leaving directory '/d/Projects/Code/yquake2remaster'
make: *** [Makefile:461: client] Error 2
´´´
Looks like make is expecting some sort of ´sdl2-config´ folder to be present somewhere. I suppose SDL cannot be bundled with the project for license reasons or something.
What to I need to do to procure the required SDL2 files for the project? Which files are required? Where should they be located? None of those things are clearly explained anywhere by anybody.
I've been struggling with this for several days, without finding any answers.
Not even the SDL repository has anything remotely useful about this.
I just want to be able to build the project.

**Comment by 0lvin** [comment]
It looks like your build environment does not have SDL and gcc installed.

Have you used pretreated build environment as described in https://github.com/yquake2/yquake2remaster/blob/master/doc/020_installation.md#prerequisites-on-windows-when-using-mingw?

**Comment by HuubVanAmelsvoort** [comment]
I use the doc [here](Compiling on Windows with Visual Studio (2015 and newer)).
Important part:
Furthermore you'll need SDL2, openal-soft and libcurl to link against.
The easiest way to get those dependencies is using the [dhewm3-libs](https://github.com/dhewm/dhewm3-libs/) together with the YQUAKE2LIBS CMake variable.
It might also be possible to manually install the dependencies or to use [vcpkg](https://vcpkg.io/) or similar to install them, but that's untested.
Use the latest master with the fix 2 days ago.

**Comment by fighterguard** [comment]
@0lvin I followed the MSVC instructions in the doc to the letter, ran the command, and still got this error:

```
cmake -G "Visual Studio 17 2022" -A x64 -DYQUAKE2LIBS=D\:Projects/Code/dhewm3/x86_64-w64-mingw32 "../remaster"

CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  stuff/cmake/modules/FindSDL2.cmake:175 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:187 (find_package)
```

In the end, the only way that worked was using the CMake GUI. That one was able to generate the .sln project, and I was finally able to build and run it.

I still don't understand why it was so difficult to make it work. And the most frustrating part is that I was able to build and run the original Yamagi project without any problems. I thought the remaster would be just as easy, but clearly, it wasn't.

Anyway, thank you very much for your patience and guidance. Now I can finally attempt to create what I've had in mind for a while now.

**Comment by HuubVanAmelsvoort** [comment]
Relative path "../remaster" is not working I think. Try to use the complete path.
