### ISSUE TITLE
All translation strings are missing. No language selection option available.

### ISSUE THREAD

**Issue by fighterguard** [yquake2/yquake2remaster#32]
![q2_strings](https://github.com/user-attachments/assets/9d05eb8c-51a7-4265-b681-f76b23963ff1)
All in-game text strings appear like this, with the translatable string variable name, instead of the corresponding translation.
Also, I haven't found any way to select a language. Maybe that's the cause of the problem, if language is null, then the engine doesn't know what to do with those translatable strings. Maybe make english the default when all else fails?

**Comment by 0lvin** [comment]
Have you have Q2Game.kpf file in n same folder as quake2 executable file? 

Code has support only English localization, it requires Q2Game.kpf file in same folder as quake2.exe.

**Comment by fighterguard** [comment]
@0lvin  I did not have that file next to the executable. Also, that file is not mention anywhere. Particularly here, where a complete list of the files required for a full gameplay experience is shown: https://github.com/yquake2/yquake2remaster/blob/master/doc/090_filelists.md
Again, I would suggest that this little tidbit of information should be added to the relevant docs.
Thank you!
