### ISSUE TITLE
How does retexture support works

### ISSUE THREAD

**Issue by Bittermens** [yquake2/yquake2remaster#5]
Something that Q2R doesn't support is map retexture support as YQ2, but it was never explained how yamagi and other ports makes textures fit with the map size textures since Q2R stretches them out.

is it possible to explain how it is it possible does this works?

**Comment by 0lvin** [comment]
With r_retexture >=2 all palette based images and cinematic is scaled 2 or 3 times by https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms if no bigger image override is availed.

With r_retexture is bigger than zero, if exist image same name and with different extension like JPG/PNG instead PNG and has bigger resolution such image used instead original one. So image just is just overrode.

**Comment by 0lvin** [comment]
Could you please reopen if you have further questions?
