### ISSUE TITLE
Compiling Error avcodec.h

### ISSUE THREAD

**Issue by acyc070** [yquake2/yquake2remaster#6]
z@z-\M-O\M-J:pty0 + /yq1: make                                                           [19:40:33]
Build configuration
============================
YQ2_ARCH = x86_64 COMPILER = gcc
WITH_CURL = yes
WITH_OPENAL = yes
WITH_RPATH = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR =
============================

===> Building yquake2.exe
make release/yquake2.exe
make[1]: Verzeichnis „/yq1“ wird betreten
===> CC src/backends/generic/misc.c
===> CC src/client/cl_cin.c
In file included from src/client/cl_cin.c:35:
src/client/cinema/avdecode.h:1:10: fatal error: libavcodec/avcodec.h: No such file or directory
    1 | #include <libavcodec/avcodec.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:440: build/client/src/client/cl_cin.o] Fehler 1
make[1]: Verzeichnis „/yq1“ wird verlassen
make: *** [Makefile:433: client] Fehler 2
zsh: exit 2     make

**Comment by 0lvin** [comment]
Build requires updated installed additional packages:
mingw-w64-i686-curl
mingw-w64-i686-ffmpeg
mingw-w64-i686-gcc
mingw-w64-i686-make
mingw-w64-i686-openal
mingw-w64-i686-SDL2
mingw-w64-i686-vulkan-headers

**Comment by 0lvin** [comment]
@acyc070 Could you please try build with packages as defined in [workflow](https://github.com/yquake2/yquake2remaster/blob/master/.github/workflows/windows.yml) or disable [avcodec](https://github.com/yquake2/yquake2remaster/blob/master/Makefile#L52)?
