### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by samyj-lucsyj-programist** [yquake2/yquake2remaster#9]
how to expand framesize to 2 bytes instead of 1

**Comment by 0lvin** [comment]
It requires to change network protocol and currently is unsupported and could/would be part of #3 with support new demo file format and extend limit for count of model used in single map.

**Comment by samyj-lucsyj-programist** [comment]
Um, I mean the engine will import md2 models with framesize 2 instead of 1.

**Comment by samyj-lucsyj-programist** [comment]
I don't think this needs to change anything with network

**Comment by 0lvin** [comment]
Do you mean model will have 512 frames but value from game library will be multiplied by two and game will see such model as model with 256 frames? As I remember md2 does not have fps/timings value in [header](https://github.com/yquake2/yquake2remaster/blob/d907b8bb57493d28a5a6129229a32be6e0d1e88d/src/common/header/files.h#L163), as result code will not able distinguish model created with current fps value and improved version. Also in such case all even frames will be skipped.

**Comment by samyj-lucsyj-programist** [comment]
I mean engine will import md2 with 16 bit vertex coords (2 bytes) instead 8 bit (1 byte)

**Comment by 0lvin** [comment]
Code is already support md2 models from Anachronox, you could use it if you like. Anachronox looks as single game where md2 format version has support 8/10/16 bit vertexes. 

Or you can use dkm2/md5 models. I am not sure about Md3, I think it still use 8bit vertex list in frame.
